apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-image-version-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-image-version-exporter
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-image-version-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-image-version-exporter
subjects:
  - kind: ServiceAccount
    name: k8s-image-version-exporter
    namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-image-version-exporter
spec:
  type: ClusterIP
  selector:
    app: k8s-image-version-exporter
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-image-version-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-image-version-exporter
  template:
    metadata:
      labels:
        app: k8s-image-version-exporter
    spec:
      serviceAccountName: k8s-image-version-exporter
      containers:
      - name: exporter
        image: kirill02102/k8s-image-version-exporter:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
